package tema_2_futbol;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Equipos.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Equipos implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID_EQUIPO. */
	private Integer idEquipo;

	/** NOMBRE. */
	private String nombre;

	/** LOCALIDAD. */
	private String localidad;

	/** The set of Jugadores. */
	private Set<Jugadores> jugadoresSet;

	/**
	 * Constructor.
	 */
	public Equipos() {
		this.jugadoresSet = new HashSet<Jugadores>();
	}

	/**
	 * Set the ID_EQUIPO.
	 * 
	 * @param idEquipo ID_EQUIPO
	 */
	public void setIdEquipo(Integer idEquipo) {
		this.idEquipo = idEquipo;
	}

	/**
	 * Get the ID_EQUIPO.
	 * 
	 * @return ID_EQUIPO
	 */
	public Integer getIdEquipo() {
		return this.idEquipo;
	}

	/**
	 * Set the NOMBRE.
	 * 
	 * @param nombre NOMBRE
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * Get the NOMBRE.
	 * 
	 * @return NOMBRE
	 */
	public String getNombre() {
		return this.nombre;
	}

	/**
	 * Set the LOCALIDAD.
	 * 
	 * @param localidad LOCALIDAD
	 */
	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	/**
	 * Get the LOCALIDAD.
	 * 
	 * @return LOCALIDAD
	 */
	public String getLocalidad() {
		return this.localidad;
	}

	/**
	 * Set the set of the Jugadores.
	 * 
	 * @param jugadoresSet The set of Jugadores
	 */
	public void setJugadoresSet(Set<Jugadores> jugadoresSet) {
		this.jugadoresSet = jugadoresSet;
	}

	/**
	 * Add the Jugadores.
	 * 
	 * @param jugadores Jugadores
	 */
	public void addJugadores(Jugadores jugadores) {
		this.jugadoresSet.add(jugadores);
	}

	/**
	 * Get the set of the Jugadores.
	 * 
	 * @return The set of Jugadores
	 */
	public Set<Jugadores> getJugadoresSet() {
		return this.jugadoresSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idEquipo == null) ? 0 : idEquipo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Equipos other = (Equipos) obj;
		if (idEquipo == null) {
			if (other.idEquipo != null) {
				return false;
			}
		} else if (!idEquipo.equals(other.idEquipo)) {
			return false;
		}
		return true;
	}
}
