package futbol;

import java.io.Serializable;

/**
 * Model class of Jugadores.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Jugadores implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID_JUGADOR. */
	private Integer idJugador;

	/** NOMBRE. */
	private String nombre;

	/** DNI. */
	private String dni;

	/** EDAD. */
	private Integer edad;

	/** POSICION. */
	private String posicion;

	/** Equipos. */
	private Equipos equipos;

	/**
	 * Constructor.
	 */
	public Jugadores() {
	}

	/**
	 * Set the ID_JUGADOR.
	 * 
	 * @param idJugador ID_JUGADOR
	 */
	public void setIdJugador(Integer idJugador) {
		this.idJugador = idJugador;
	}

	/**
	 * Get the ID_JUGADOR.
	 * 
	 * @return ID_JUGADOR
	 */
	public Integer getIdJugador() {
		return this.idJugador;
	}

	/**
	 * Set the NOMBRE.
	 * 
	 * @param nombre NOMBRE
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * Get the NOMBRE.
	 * 
	 * @return NOMBRE
	 */
	public String getNombre() {
		return this.nombre;
	}

	/**
	 * Set the DNI.
	 * 
	 * @param dni DNI
	 */
	public void setDni(String dni) {
		this.dni = dni;
	}

	/**
	 * Get the DNI.
	 * 
	 * @return DNI
	 */
	public String getDni() {
		return this.dni;
	}

	/**
	 * Set the EDAD.
	 * 
	 * @param edad EDAD
	 */
	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	/**
	 * Get the EDAD.
	 * 
	 * @return EDAD
	 */
	public Integer getEdad() {
		return this.edad;
	}

	/**
	 * Set the POSICION.
	 * 
	 * @param posicion POSICION
	 */
	public void setPosicion(String posicion) {
		this.posicion = posicion;
	}

	/**
	 * Get the POSICION.
	 * 
	 * @return POSICION
	 */
	public String getPosicion() {
		return this.posicion;
	}

	/**
	 * Set the Equipos.
	 * 
	 * @param equipos Equipos
	 */
	public void setEquipos(Equipos equipos) {
		this.equipos = equipos;
	}

	/**
	 * Get the Equipos.
	 * 
	 * @return Equipos
	 */
	public Equipos getEquipos() {
		return this.equipos;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idJugador == null) ? 0 : idJugador.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Jugadores other = (Jugadores) obj;
		if (idJugador == null) {
			if (other.idJugador != null) {
				return false;
			}
		} else if (!idJugador.equals(other.idJugador)) {
			return false;
		}
		return true;
	}
}
