package tema_2.examen;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of AUTORES.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AutoresEjercicio2 implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID_AUTOR. */
	private Integer idAutor;

	/** NOMBRE_AUTOR. */
	private String nombreAutor;

	/** The set of ENCICLOPEDIAS. */
	private Set<EnciclopediasEjercicio2> enciclopediasSet;

	/**
	 * Constructor.
	 */
	public AutoresEjercicio2() {
		this.enciclopediasSet = new HashSet<EnciclopediasEjercicio2>();
	}

	/**
	 * Set the ID_AUTOR.
	 * 
	 * @param idAutor
	 *            ID_AUTOR
	 */
	public void setIdAutor(Integer idAutor) {
		this.idAutor = idAutor;
	}

	/**
	 * Get the ID_AUTOR.
	 * 
	 * @return ID_AUTOR
	 */
	public Integer getIdAutor() {
		return this.idAutor;
	}

	/**
	 * Set the NOMBRE_AUTOR.
	 * 
	 * @param nombreAutor
	 *            NOMBRE_AUTOR
	 */
	public void setNombreAutor(String nombreAutor) {
		this.nombreAutor = nombreAutor;
	}

	/**
	 * Get the NOMBRE_AUTOR.
	 * 
	 * @return NOMBRE_AUTOR
	 */
	public String getNombreAutor() {
		return this.nombreAutor;
	}

	/**
	 * Set the set of the ENCICLOPEDIAS.
	 * 
	 * @param enciclopediasSet
	 *            The set of ENCICLOPEDIAS
	 */
	public void setEnciclopediasSet(Set<EnciclopediasEjercicio2> enciclopediasSet) {
		this.enciclopediasSet = enciclopediasSet;
	}

	/**
	 * Add the ENCICLOPEDIAS.
	 * 
	 * @param enciclopedias
	 *            ENCICLOPEDIAS
	 */
	public void addEnciclopedias(EnciclopediasEjercicio2 enciclopedias) {
		this.enciclopediasSet.add(enciclopedias);
	}

	/**
	 * Get the set of the ENCICLOPEDIAS.
	 * 
	 * @return The set of ENCICLOPEDIAS
	 */
	public Set<EnciclopediasEjercicio2> getEnciclopediasSet() {
		return this.enciclopediasSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idAutor == null) ? 0 : idAutor.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AutoresEjercicio2 other = (AutoresEjercicio2) obj;
		if (idAutor == null) {
			if (other.idAutor != null) {
				return false;
			}
		} else if (!idAutor.equals(other.idAutor)) {
			return false;
		}
		return true;
	}

}
