package tema_2.examen;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of ENCICLOPEDIAS.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EnciclopediasEjercicio2 implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID_ENCICLOPEDIA. */
	private Integer idEnciclopedia;

	/** NOMBRE. */
	private String nombre;

	/** ISBN. */
	private String isbn;

	/** EDITORIAL. */
	private String editorial;

	/** FECHA_PUBLICACION. */
	private Date fechaPublicacion;

	/** AUTORES. */
	private AutoresEjercicio2 autores;

	/** The set of TOMOS. */
	private Set<TomosEjercicio2> tomosSet;

	/**
	 * Constructor.
	 */
	public EnciclopediasEjercicio2() {
		this.tomosSet = new HashSet<TomosEjercicio2>();
	}

	/**
	 * Set the ID_ENCICLOPEDIA.
	 * 
	 * @param idEnciclopedia
	 *            ID_ENCICLOPEDIA
	 */
	public void setIdEnciclopedia(Integer idEnciclopedia) {
		this.idEnciclopedia = idEnciclopedia;
	}

	/**
	 * Get the ID_ENCICLOPEDIA.
	 * 
	 * @return ID_ENCICLOPEDIA
	 */
	public Integer getIdEnciclopedia() {
		return this.idEnciclopedia;
	}

	/**
	 * Set the NOMBRE.
	 * 
	 * @param nombre
	 *            NOMBRE
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * Get the NOMBRE.
	 * 
	 * @return NOMBRE
	 */
	public String getNombre() {
		return this.nombre;
	}

	/**
	 * Set the ISBN.
	 * 
	 * @param isbn
	 *            ISBN
	 */
	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	/**
	 * Get the ISBN.
	 * 
	 * @return ISBN
	 */
	public String getIsbn() {
		return this.isbn;
	}

	/**
	 * Set the EDITORIAL.
	 * 
	 * @param editorial
	 *            EDITORIAL
	 */
	public void setEditorial(String editorial) {
		this.editorial = editorial;
	}

	/**
	 * Get the EDITORIAL.
	 * 
	 * @return EDITORIAL
	 */
	public String getEditorial() {
		return this.editorial;
	}

	/**
	 * Set the FECHA_PUBLICACION.
	 * 
	 * @param fechaPublicacion
	 *            FECHA_PUBLICACION
	 */
	public void setFechaPublicacion(Date fechaPublicacion) {
		this.fechaPublicacion = fechaPublicacion;
	}

	/**
	 * Get the FECHA_PUBLICACION.
	 * 
	 * @return FECHA_PUBLICACION
	 */
	public Date getFechaPublicacion() {
		return this.fechaPublicacion;
	}

	/**
	 * Set the AUTORES.
	 * 
	 * @param autores
	 *            AUTORES
	 */
	public void setAutores(AutoresEjercicio2 autores) {
		this.autores = autores;
	}

	/**
	 * Get the AUTORES.
	 * 
	 * @return AUTORES
	 */
	public AutoresEjercicio2 getAutores() {
		return this.autores;
	}

	/**
	 * Set the set of the TOMOS.
	 * 
	 * @param tomosSet
	 *            The set of TOMOS
	 */
	public void setTomosSet(Set<TomosEjercicio2> tomosSet) {
		this.tomosSet = tomosSet;
	}

	/**
	 * Add the TOMOS.
	 * 
	 * @param tomos
	 *            TOMOS
	 */
	public void addTomos(TomosEjercicio2 tomos) {
		this.tomosSet.add(tomos);
	}

	/**
	 * Get the set of the TOMOS.
	 * 
	 * @return The set of TOMOS
	 */
	public Set<TomosEjercicio2> getTomosSet() {
		return this.tomosSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idEnciclopedia == null) ? 0 : idEnciclopedia.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		EnciclopediasEjercicio2 other = (EnciclopediasEjercicio2) obj;
		if (idEnciclopedia == null) {
			if (other.idEnciclopedia != null) {
				return false;
			}
		} else if (!idEnciclopedia.equals(other.idEnciclopedia)) {
			return false;
		}
		return true;
	}

}
