package tema_2.examen;

import java.io.Serializable;

/**
 * Model class of TOMOS.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TomosEjercicio2 implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID_TOMO. */
	private Integer idTomo;

	/** NOMBRE_TOMO. */
	private String nombreTomo;

	/** ENCICLOPEDIAS. */
	private EnciclopediasEjercicio2 enciclopedias;

	/**
	 * Constructor.
	 */
	public TomosEjercicio2() {
	}

	/**
	 * Set the ID_TOMO.
	 * 
	 * @param idTomo
	 *            ID_TOMO
	 */
	public void setIdTomo(Integer idTomo) {
		this.idTomo = idTomo;
	}

	/**
	 * Get the ID_TOMO.
	 * 
	 * @return ID_TOMO
	 */
	public Integer getIdTomo() {
		return this.idTomo;
	}

	/**
	 * Set the NOMBRE_TOMO.
	 * 
	 * @param nombreTomo
	 *            NOMBRE_TOMO
	 */
	public void setNombreTomo(String nombreTomo) {
		this.nombreTomo = nombreTomo;
	}

	/**
	 * Get the NOMBRE_TOMO.
	 * 
	 * @return NOMBRE_TOMO
	 */
	public String getNombreTomo() {
		return this.nombreTomo;
	}

	/**
	 * Set the ENCICLOPEDIAS.
	 * 
	 * @param enciclopedias
	 *            ENCICLOPEDIAS
	 */
	public void setEnciclopedias(EnciclopediasEjercicio2 enciclopedias) {
		this.enciclopedias = enciclopedias;
	}

	/**
	 * Get the ENCICLOPEDIAS.
	 * 
	 * @return ENCICLOPEDIAS
	 */
	public EnciclopediasEjercicio2 getEnciclopedias() {
		return this.enciclopedias;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idTomo == null) ? 0 : idTomo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		TomosEjercicio2 other = (TomosEjercicio2) obj;
		if (idTomo == null) {
			if (other.idTomo != null) {
				return false;
			}
		} else if (!idTomo.equals(other.idTomo)) {
			return false;
		}
		return true;
	}

}
